## It's easier to do by Scikit-Learn :)

In [2]:
!pip install category_encoders

Collecting category_encoders
  Downloading category_encoders-2.3.0-py2.py3-none-any.whl (82 kB)
Requirement already satisfied: numpy>=1.14.0 in c:\users\mamagdy\appdata\local\continuum\anaconda3\lib\site-packages (from category_encoders) (1.19.5)
Requirement already satisfied: statsmodels>=0.9.0 in c:\users\mamagdy\appdata\local\continuum\anaconda3\lib\site-packages (from category_encoders) (0.11.0)
Requirement already satisfied: patsy>=0.5.1 in c:\users\mamagdy\appdata\local\continuum\anaconda3\lib\site-packages (from category_encoders) (0.5.1)
Requirement already satisfied: scipy>=1.0.0 in c:\users\mamagdy\appdata\local\continuum\anaconda3\lib\site-packages (from category_encoders) (1.5.4)
Requirement already satisfied: scikit-learn>=0.20.0 in c:\users\mamagdy\appdata\local\continuum\anaconda3\lib\site-packages (from category_encoders) (0.24.2)
Requirement already satisfied: pandas>=0.21.1 in c:\users\mamagdy\appdata\roaming\python\python37\site-packages (from category_encoders) (1.3.5)
Requirement already satisfied: six in c:\users\mamagdy\appdata\local\continuum\anaconda3\lib\site-packages (from patsy>=0.5.1->category_encoders) (1.14.0)
Requirement already satisfied: joblib>=0.11 in c:\users\mamagdy\appdata\local\continuum\anaconda3\lib\site-packages (from scikit-learn>=0.20.0->category_encoders) (0.14.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\mamagdy\appdata\local\continuum\anaconda3\lib\site-packages (from scikit-learn>=0.20.0->category_encoders) (3.0.0)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\mamagdy\appdata\local\continuum\anaconda3\lib\site-packages (from pandas>=0.21.1->category_encoders) (2.8.1)
Requirement already satisfied: pytz>=2017.3 in c:\users\mamagdy\appdata\local\continuum\anaconda3\lib\site-packages (from pandas>=0.21.1->category_encoders) (2019.3)
Installing collected packages: category-encoders
Successfully installed category-encoders-2.3.0

In [26]:
import pandas as pd
import category_encoders as ce

In [27]:
df = pd.read_csv('../datasets/surveys.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35549 entries, 0 to 35548
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   record_id        35549 non-null  int64
 1   month            35549 non-null  int64
 2   day              35549 non-null  int64
 3   year             35549 non-null  int64
 4   plot_id          35549 non-null  int64
 5   species_id       34786 non-null  object
 6   sex              33038 non-null  object
 7   hindfoot_length  31438 non-null  float64
 8   weight           32283 non-null  float64
dtypes: float64(2), int64(5), object(2)
memory usage: 2.4+ MB

In [28]:
df

,record_id,month,day,year,plot_id,species_id,sex,hindfoot_length,weight
0,1,7,16,1977,2,NL,M,32.0,NaN
1,2,7,16,1977,3,NL,M,33.0,NaN
2,3,7,16,1977,2,DM,F,37.0,NaN
3,4,7,16,1977,7,DM,M,36.0,NaN
4,5,7,16,1977,3,DM,M,35.0,NaN
...,...,...,...,...,...,...,...,...,...
35544,35545,12,31,2002,15,AH,NaN,NaN,NaN
35545,35546,12,31,2002,15,AH,NaN,NaN,NaN
35546,35547,12,31,2002,10,RM,F,15.0,14.0
35547,35548,12,31,2002,7,DO,M,36.0,51.0
35548,35549,12,31,2002,5,NaN,NaN,NaN,NaN

In [29]:
binaryEncoder = ce.BinaryEncoder()

In [30]:
binaryEncoder.fit_transform(df[['sex', 'species_id']])

,sex_0,sex_1,species_id_0,species_id_1,species_id_2,species_id_3,species_id_4,species_id_5
0,0,1,0,0,0,0,0,1
1,0,1,0,0,0,0,0,1
2,1,0,0,0,0,0,1,0
3,0,1,0,0,0,0,1,0
4,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...
35544,1,1,0,1,0,0,0,1
35545,1,1,0,1,0,0,0,1
35546,1,0,0,0,1,1,0,1
35547,0,1,0,0,1,0,0,1
35548,1,1,0,0,1,1,1,0

In [31]:
df = pd.concat([df, binaryEncoder.fit_transform(df[['sex', 'species_id']])], axis=1)
del df['sex']
del df['species_id']
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35549 entries, 0 to 35548
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   record_id        35549 non-null  int64
 1   month            35549 non-null  int64
 2   day              35549 non-null  int64
 3   year             35549 non-null  int64
 4   plot_id          35549 non-null  int64
 5   hindfoot_length  31438 non-null  float64
 6   weight           32283 non-null  float64
 7   sex_0            35549 non-null  int64
 8   sex_1            35549 non-null  int64
 9   species_id_0     35549 non-null  int64
 10  species_id_1     35549 non-null  int64
 11  species_id_2     35549 non-null  int64
 12  species_id_3     35549 non-null  int64
 13  species_id_4     35549 non-null  int64
 14  species_id_5     35549 non-null  int64
dtypes: float64(2), int64(13)
memory usage: 4.1 MB

In [32]:
df.head()

,record_id,month,day,year,plot_id,hindfoot_length,weight,sex_0,sex_1,species_id_0,species_id_1,species_id_2,species_id_3,species_id_4,species_id_5
0,1,7,16,1977,2,32.0,NaN,0,1,0,0,0,0,0,1
1,2,7,16,1977,3,33.0,NaN,0,1,0,0,0,0,0,1
2,3,7,16,1977,2,37.0,NaN,1,0,0,0,0,0,1,0
3,4,7,16,1977,7,36.0,NaN,0,1,0,0,0,0,1,0
4,5,7,16,1977,3,35.0,NaN,0,1,0,0,0,0,1,0

### Congratulations, we achieved the Binary Encoding in an easy way :)