In [1]:
!pip install bar_chart_race

Collecting bar_chart_race
  Downloading bar_chart_race-0.1.0-py3-none-any.whl (156 kB)
Requirement already satisfied: pandas>=0.24 in c:\users\mamagdy\appdata\local\continuum\anaconda3\lib\site-packages (from bar_chart_race) (1.0.2)
Requirement already satisfied: matplotlib>=3.1 in c:\users\mamagdy\appdata\local\continuum\anaconda3\lib\site-packages (from bar_chart_race) (3.1.3)
Requirement already satisfied: pytz>=2017.2 in c:\users\mamagdy\appdata\local\continuum\anaconda3\lib\site-packages (from pandas>=0.24->bar_chart_race) (2019.3)
Requirement already satisfied: numpy>=1.13.3 in c:\users\mamagdy\appdata\local\continuum\anaconda3\lib\site-packages (from pandas>=0.24->bar_chart_race) (1.18.1)
Requirement already satisfied: python-dateutil>=2.6.1 in c:\users\mamagdy\appdata\local\continuum\anaconda3\lib\site-packages (from pandas>=0.24->bar_chart_race) (2.8.1)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\mamagdy\appdata\local\continuum\anaconda3\lib\site-packages (from matplotlib>=3.1->bar_chart_race) (1.1.0)
Requirement already satisfied: cycler>=0.10 in c:\users\mamagdy\appdata\local\continuum\anaconda3\lib\site-packages (from matplotlib>=3.1->bar_chart_race) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in c:\users\mamagdy\appdata\local\continuum\anaconda3\lib\site-packages (from matplotlib>=3.1->bar_chart_race) (2.4.6)
Requirement already satisfied: six>=1.5 in c:\users\mamagdy\appdata\local\continuum\anaconda3\lib\site-packages (from python-dateutil>=2.6.1->pandas>=0.24->bar_chart_race) (1.14.0)
Requirement already satisfied: setuptools in c:\users\mamagdy\appdata\local\continuum\anaconda3\lib\site-packages (from kiwisolver>=1.0.1->matplotlib>=3.1->bar_chart_race) (46.0.0.post20200309)
Installing collected packages: bar-chart-race
Successfully installed bar-chart-race-0.1.0

In [1]:
import pandas as pd

In [2]:
import bar_chart_race as bcr

In [3]:
df = pd.read_csv("https://raw.githubusercontent.com/dexplo/bar_chart_race/master/data/urban_pop.csv")

In [4]:
df.head()

,year,United States,India,China,Ethiopia,Poland,Malaysia,Peru,Venezuela,Iraq,...,Iran,Turkey,Germany,Pakistan,Nigeria,Mexico,Russia,Japan,Indonesia,Brazil
0,1976,160611122,138219074,162497601,3194879,19215135,4802814,9834645,10382196,7530612,...,15742290,16914583,56885943,18365687,13177979,38883279,90810675,85642808,26596457,67790415
1,1977,162256678,143699557,165293316,3300643,19625330,5038232,10197056,10778965,7901451,...,16521005,17474315,56801863,19175026,13868037,40371908,92479950,86538157,28001978,70478354
2,1978,164005080,149379782,171153535,3406129,20007316,5284698,10567468,11185526,8253727,...,17336704,18048189,56796181,20032626,14598364,41879098,94157479,87391419,29468690,73245834
3,1979,165847531,155285824,180399661,3522584,20341874,5539880,10945723,11600322,8598800,...,18227951,18640066,56865826,20941767,15355488,43407693,95659612,88197927,30996679,76091693
4,1980,167551171,161444128,189947471,3658252,20663601,5801267,11331194,12022351,8945814,...,19206467,19252680,57028530,21906732,16131172,44952217,96960865,88958689,32591870,79015954

In [5]:
df = df.set_index('year')

In [6]:
df.head()

,United States,India,China,Ethiopia,Poland,Malaysia,Peru,Venezuela,Iraq,Saudi Arabia,...,Iran,Turkey,Germany,Pakistan,Nigeria,Mexico,Russia,Japan,Indonesia,Brazil
year,,,,,,,,,,,,,,,,,,,,,
1976,160611122,138219074,162497601,3194879,19215135,4802814,9834645,10382196,7530612,4673719,...,15742290,16914583,56885943,18365687,13177979,38883279,90810675,85642808,26596457,67790415
1977,162256678,143699557,165293316,3300643,19625330,5038232,10197056,10778965,7901451,5041250,...,16521005,17474315,56801863,19175026,13868037,40371908,92479950,86538157,28001978,70478354
1978,164005080,149379782,171153535,3406129,20007316,5284698,10567468,11185526,8253727,5441027,...,17336704,18048189,56796181,20032626,14598364,41879098,94157479,87391419,29468690,73245834
1979,165847531,155285824,180399661,3522584,20341874,5539880,10945723,11600322,8598800,5885282,...,18227951,18640066,56865826,20941767,15355488,43407693,95659612,88197927,30996679,76091693
1980,167551171,161444128,189947471,3658252,20663601,5801267,11331194,12022351,8945814,6382806,...,19206467,19252680,57028530,21906732,16131172,44952217,96960865,88958689,32591870,79015954

In [7]:
df.columns

Index(['United States', 'India', 'China', 'Ethiopia', 'Poland', 'Malaysia',
       'Peru', 'Venezuela', 'Iraq', 'Saudi Arabia', 'Canada', 'Algeria',
       'Ukraine', 'Vietnam', 'Thailand', 'Congo, Dem. Rep.', 'Spain',
       'South Africa', 'Colombia', 'Argentina', 'Egypt', 'South Korea',
       'Italy', 'Philippines', 'France', 'United Kingdom', 'Bangladesh',
       'Iran', 'Turkey', 'Germany', 'Pakistan', 'Nigeria', 'Mexico', 'Russia',
       'Japan', 'Indonesia', 'Brazil'],
      dtype='object')

In [8]:
bcr.bar_chart_race(df = df, title = "Population Growth")

In [9]:
bcr.bar_chart_race(df = df, title = "Population Growth",n_bars=10, orientation='h', cmap = 'prism')

You will need to follow what mentioned here https://stackoverflow.com/a/44483126, if you met the ffmpeg error

It's good to read this to know more about the parameters: https://www.dunderdata.com/blog/official-release-of-bar_chart_race-a-python-package-for-creating-animated-bar-chart-races